# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-14 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_remove_user_following'),
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
