# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='Bio Will Appear Here', max_length=300),
        ),
    ]
